nginx:
  image: nginx:1.13
  ports:
    - 80:80
  links:
    - php
  volumes:
    - ./:/var/www/default:Z
    - ./docker/nginx/hosts:/etc/nginx/conf.d
    - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf

php:
  build: ./docker/php
  ports:
    - 9000:9000
  links:
    - mysql
  volumes:
    - ./:/var/www/default


mysql:
  image: mysql:5.7.19
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: pass123
    MYSQL_DATABASE: calendar
    MYSQL_USER: calendar_user
    MYSQL_PASSWORD: calendar_pass


phpmyadmin:
  image: phpmyadmin/phpmyadmin:4.7
  links:
    - mysql
  ports:
    - 8080:80
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
    PMA_USER: calendar_user
    PMA_PASSWORD: calendar_pass
    PMA_ARBITRARy: 1